# Generated by Django 5.0.2 on 2024-03-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='logo_clavier.jpg')),
                ('quantite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adp', models.CharField(max_length=400)),
                ('cp', models.CharField(max_length=20)),
                ('ville', models.CharField(max_length=100)),
                ('adm', models.CharField(max_length=400)),
                ('adt', models.CharField(max_length=50)),
                ('produits', models.ManyToManyField(to='stock.produit')),
            ],
        ),
    ]
