# Generated by Django 5.0.2 on 2024-03-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magasin',
            name='nom',
            field=models.CharField(default='Magasin', max_length=200),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.FloatField(default=0),
        ),
    ]
